import './utils/menu.js'
import './utils/sliders.js'
import './utils/header.js'
import './utils/open-characteristics.js'
import './utils/popup-form.js'
import './utils/filter.js'
import './utils/gallery.js'
